apiVersion: v1
kind: Service
metadata:
  name: node1
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node1 }
  ports:
    - name: app-port        
      port: 5000
      targetPort: 5000

   

---

apiVersion: v1
kind: Service
metadata:
  name: node2
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node2 }
  ports:
    - name: app-port     
      port: 5000
      targetPort: 5000
 
   

---

apiVersion: v1
kind: Service
metadata:
  name: node3
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node3 }
  ports:
    - name: app-port      
      port: 5000
      targetPort: 5000
 
   

---

apiVersion: v1
kind: Service
metadata:
  name: node4
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node4 }
  ports:
    - name: app-port        
      port: 5000
      targetPort: 5000

  

---

apiVersion: v1
kind: Service
metadata:
  name: node5
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node5 }
  ports:
    - name: app-port        
      port: 5000
      targetPort: 5000
   


---

apiVersion: v1
kind: Service
metadata:
  name: node6
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node6 }
  ports:
    - name: app-port      
      port: 5000
      targetPort: 5000
 
 

---

apiVersion: v1
kind: Service
metadata:
  name: node7
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node7 }
  ports:
    - name: app-port      
      port: 5000
      targetPort: 5000
 
   

---

apiVersion: v1
kind: Service
metadata:
  name: node8
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node8 }
  ports:
    - name: app-port       
      port: 5000
      targetPort: 5000
  
  

---

apiVersion: v1
kind: Service
metadata:
  name: node9
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node9 }
  ports:
    - name: app-port        
      port: 5000
      targetPort: 5000

  

---

apiVersion: v1
kind: Service
metadata:
  name: node10
  namespace: nodes
  labels:
    app: node
spec:
  selector: { app: node10 }
  ports:
    - name: app-port       
      port: 5000
      targetPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: node-graph-exporter
  namespace: monitoring
  labels:
    app: node-graph-exporter
spec:
  selector:
    app: node-graph-exporter
  ports:
  - name: http
    port: 9101
    targetPort: 9101






 


