global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'  # LE PONEMOS NOMBRE AL JOB 
    static_configs:
      - targets: ['prometheus:9090'] # LE DECIMOS LA RUTA DONDE ESTA EL SERVICIO (HOST:PUERTO)
    
  - job_name: 'nodos'
    static_configs:
      - targets:
          - 'node1:8000'
          - 'node2:8000'
          - 'node3:8000'
          - 'node4:8000'
          - 'node5:8000'
          - 'node6:8000'
          - 'node7:8000'
          - 'node8:8000'
          - 'node9:8000'
          - 'node10:8000'
